<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>gov51-ps4</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="gov51-ps4_files/libs/clipboard/clipboard.min.js"></script>
<script src="gov51-ps4_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="gov51-ps4_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="gov51-ps4_files/libs/quarto-html/popper.min.js"></script>
<script src="gov51-ps4_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="gov51-ps4_files/libs/quarto-html/anchor.min.js"></script>
<link href="gov51-ps4_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="gov51-ps4_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="gov51-ps4_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="gov51-ps4_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="gov51-ps4_files/libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">gov51-ps4</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="gov-51-pset-4" class="level2">
<h2 class="anchored" data-anchor-id="gov-51-pset-4">Gov 51 PSET 4</h2>
<p><a href="https://github.com/sagepiekarski-ai/gov51-ps4.git" class="uri">https://github.com/sagepiekarski-ai/gov51-ps4.git</a></p>
<section id="sage-piekarski" class="level3">
<h3 class="anchored" data-anchor-id="sage-piekarski">Sage Piekarski</h3>
<section id="setup-and-exploration" class="level4">
<h4 class="anchored" data-anchor-id="setup-and-exploration">1 Setup and Exploration</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#1.1</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>())</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'</span><span class="sc">\014</span><span class="st">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div style="page-break-after: always;"></div>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Install and load packages</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(tidyverse)) <span class="fu">install.packages</span>(<span class="st">"tidyverse"</span>); <span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: tidyverse</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.2
✔ ggplot2   4.0.2     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0     </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(estimatr)) <span class="fu">install.packages</span>(<span class="st">"estimatr"</span>); <span class="fu">library</span>(estimatr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: estimatr</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(modelsummary)) <span class="fu">install.packages</span>(<span class="st">"modelsummary"</span>); <span class="fu">library</span>(modelsummary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: modelsummary</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'modelsummary' was built under R version 4.5.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>card <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Data/card1995.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 3010 Columns: 16
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (16): wage, lwage, educ, nearc4, nearc2, black, smsa, south, exper, expe...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p><strong>1.2 Describe the data</strong></p>
<p>In the dataset there are 3010 observations. The unit of observations are individual workers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#1.3</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> card, <span class="fu">aes</span>(<span class="at">x =</span> educ))<span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">15</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">fill =</span> <span class="st">"cornflowerblue"</span>) <span class="sc">+</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Years of Completed Education"</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Years of Completed Education (endogenous variable)"</span>,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="gov51-ps4_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(card<span class="sc">$</span>educ, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.26346</code></pre>
</div>
</div>
<p><strong>1.3 Distribution of years of education</strong></p>
<p>The mean is 13.263. Based on the histogram there appear to be large spikes at about 12 years of education and 16 years of education. Conceptually, it makes sense that there would be spikes here because 12 years of education is associated with completion of a high school degree, and 16 years would be consistent with completion of a bachelors degree. It makes sense that people would stop with education at these milestone points.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#1.4</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> card, <span class="fu">aes</span>(<span class="at">x=</span>educ, <span class="at">y=</span>lwage))<span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>)<span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"cornflowerblue"</span>)<span class="sc">+</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Log Weekly Wage vs. Years of Completed Education"</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Years of Completed Education (endogenous variable)"</span>,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Log Weekly Wage (outcome)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="gov51-ps4_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>1.4 The naïve relationship</strong></p>
<p>Based on this plot, more education does appear to be associated with higher wages as can be seen by the positive slope of our linear regression line.</p>
<p><strong>1.5 Why OLS might be misleading</strong></p>
<p>The OLS regression of lwage on educ might not give us the causal effect of education. One reason why people with more education might earn more even if education itself had no effect is because people with more education, may be those with more financial resources to go to school for longer, and these financial resources also allow them to have more more connections and better job opportunities via a higher earning network. Another reason why people with more education might earn more even if education itself has no effect, is if people who get more education are fundamentally those that have higher performance abilities. As a result, these people are also more systematically likely to do better at work, have better job, and have higher earnings.</p>
</section>
<section id="the-instrument-college-proximity" class="level4">
<h4 class="anchored" data-anchor-id="the-instrument-college-proximity">2 The Instrument: College Proximity</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(card<span class="sc">$</span>nearc4, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6820598</code></pre>
</div>
</div>
<p><strong>2.1 What the instrument measures</strong></p>
<p>The variable nearc4 equals 1 if the respondent grew up near a 4-year college. The share of respondents in this sample that grew up near a 4-year college is 0.682 or about 68.2%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#2.2</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>first_stage <span class="ot">&lt;-</span> <span class="fu">lm_robust</span>(educ <span class="sc">~</span> nearc4 <span class="sc">+</span> black <span class="sc">+</span> smsa <span class="sc">+</span> south <span class="sc">+</span> exper <span class="sc">+</span> expersq <span class="sc">+</span> married,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data =</span> card, <span class="at">se_type =</span> <span class="st">"HC2"</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>first_stage</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Estimate Std. Error     t value     Pr(&gt;|t|)     CI Lower
(Intercept) 16.946910655 0.16094303 105.2975739 0.000000e+00 16.631340582
nearc4       0.327111413 0.08055446   4.0607488 5.016911e-05  0.169163750
black       -0.945290863 0.08859855 -10.6693722 4.142485e-26 -1.119011027
smsa         0.423328089 0.08521067   4.9680176 7.143751e-07  0.256250732
south       -0.300175660 0.07857125  -3.8204260 1.359266e-04 -0.454234747
exper       -0.432445687 0.03238761 -13.3521954 1.519509e-39 -0.495949899
expersq      0.001409957 0.00170720   0.8258884 4.089332e-01 -0.001937447
married     -0.074408252 0.01767034  -4.2109124 2.618347e-05 -0.109055482
                CI Upper   DF
(Intercept) 17.262480728 2995
nearc4       0.485059075 2995
black       -0.771570699 2995
smsa         0.590405447 2995
south       -0.146116572 2995
exper       -0.368941476 2995
expersq      0.004757361 2995
married     -0.039761021 2995</code></pre>
</div>
</div>
<p><strong>2.2 Relevance: does proximity affect education?</strong></p>
<p>The coeﬀicient on nearc4 is 0.327 and its standard error is 0.081. The t-statistic is 4.061. This indicates that living near a 4-year college at age 14 was on average associated with the completion of an additional 0.327 years of education holding constant being black, lived in a metropolitan area, lived in the South, potential labor market experience (years), experience squared, and married. The positive sign makes sense because if one lives near a college as a child they likely experienced a reduced cost of education meaning it is easier and cheaper for them to go to college.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>F <span class="ot">&lt;-</span> <span class="fl">4.0607488</span><span class="sc">^</span><span class="dv">2</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>F</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16.48968</code></pre>
</div>
</div>
<p><strong>2.3 Checking instrument strength</strong></p>
<p>The t-statistic on nearc4 from the first-stage regression was 4.061. The first-stage F-statistic is 16.490. Our instrument is strong because 16.49 &gt; 10. Instrument strength matters for the reliability of the 2SLS estimate because the point of including instrumental vairables is to establish a causal relationship and if you include a weak instrument it leaves a lot of room for variability, imprecision and bias.</p>
<p><strong>2.4 Exclusion restriction</strong></p>
<p>The second condition for a valid instrument is the exclusion restriction: college proximity must affect wages only through its effect on education — not through any other channel. (a) The exclusion restriction in this example is that it must be true that once we control for education, nearc4 must only affect lwage through its affect on educ. (b) One way the exclusion restriction might be violated is that areas around colleges may systematically differ in terms of racial segregation or racial profiling. In this case, employers around colleges may differ in hiring discrimination than in other areas. Perhaps near these areas employers discriminate less throughout the hiring process, so if you are a person of color and live in this area you may have other wages than those that do no live near colleges.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#2.5</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>card_summ <span class="ot">&lt;-</span> card <span class="sc">%&gt;%</span> </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(nearc4) <span class="sc">%&gt;%</span> </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_black =</span> <span class="fu">mean</span>(black),</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">mean_smsa =</span> <span class="fu">mean</span>(smsa),</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">mean_south =</span> <span class="fu">mean</span>(south))</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>card_summ</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  nearc4 mean_black mean_smsa mean_south
   &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
1      0      0.280     0.479      0.563
2      1      0.212     0.822      0.329</code></pre>
</div>
</div>
<p>2.5 Balance check</p>
<p>The groups do not appear to be balanced. If we look at the table there appear to be slightly less black people that lived near colleges, there appear to be a substantial amount more people that lived in a metropolitan area that lived near colleges, and there appear to be less people that lived in the south that lived near colleges. These imbalances tell us that there may be a lot of outside variables affecting wage. In our study black, smsa, and south are not randomly assigned and nearc4 is likely not as good as randomly assigned so exogeneity could be a threat to the validity of the instrument.</p>
</section>
<section id="the-wald-estimator" class="level4">
<h4 class="anchored" data-anchor-id="the-wald-estimator">3 The Wald Estimator</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#3.1</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>reduced_form <span class="ot">&lt;-</span> <span class="fu">lm_robust</span>(lwage <span class="sc">~</span> nearc4 <span class="sc">+</span> black <span class="sc">+</span> smsa <span class="sc">+</span> south <span class="sc">+</span> exper <span class="sc">+</span> expersq <span class="sc">+</span> married,</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">data =</span> card, <span class="at">se_type =</span> <span class="st">"HC2"</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>reduced_form</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Estimate   Std. Error    t value     Pr(&gt;|t|)     CI Lower
(Intercept)  6.104783907 0.0369399692 165.262290 0.000000e+00  6.032353626
nearc4       0.040854001 0.0160992779   2.537629 1.121090e-02  0.009287240
black       -0.236173434 0.0183381490 -12.878804 5.575495e-37 -0.272130077
smsa         0.196878652 0.0166562312  11.820120 1.526619e-31  0.164219841
south       -0.146503379 0.0163740318  -8.947300 6.243086e-19 -0.178608866
exper        0.040915614 0.0067799803   6.034769 1.787335e-09  0.027621724
expersq     -0.001789075 0.0003227884  -5.542562 3.239634e-08 -0.002421984
married     -0.038825630 0.0038391643 -10.113042 1.154798e-23 -0.046353296
                CI Upper   DF
(Intercept)  6.177214187 2995
nearc4       0.072420763 2995
black       -0.200216791 2995
smsa         0.229537464 2995
south       -0.114397892 2995
exper        0.054209503 2995
expersq     -0.001156165 2995
married     -0.031297964 2995</code></pre>
</div>
</div>
<p><strong>3.1 Compute the reduced form</strong></p>
<p>The coeﬀicient on nearc4 is 0.041. This tells us that those that living near a college is on average associated with approximately a 4.1% increase in wages, holding constant being black, lived in a metropolitan area, lived in the South, potential labor market experience (years), experience squared, and married.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#3.2</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>fstage_coeff <span class="ot">&lt;-</span> <span class="fl">0.327111413</span> </span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>rform_coeff <span class="ot">&lt;-</span> <span class="fl">0.040854001</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>wald_estimator <span class="ot">&lt;-</span> rform_coeff<span class="sc">/</span>fstage_coeff</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>wald_estimator</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1248932</code></pre>
</div>
</div>
<p><strong>3.2 Calculate the Wald estimator by hand</strong></p>
<p>The Wald estimator is 0.125.</p>
<p><strong>3.3 Interpret the Wald estimator</strong></p>
<p>The wald estimate says that the effect of one additional year of education changes the outcome, wages, by +12.5%.</p>
</section>
<section id="ols-vs-2sls" class="level4">
<h4 class="anchored" data-anchor-id="ols-vs-2sls">4 OLS vs 2SLS</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">#4.1</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>ols <span class="ot">&lt;-</span> <span class="fu">lm_robust</span>(lwage <span class="sc">~</span> educ <span class="sc">+</span> black <span class="sc">+</span> smsa <span class="sc">+</span> south <span class="sc">+</span> exper <span class="sc">+</span> expersq <span class="sc">+</span> married,</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> card, <span class="at">se_type =</span> <span class="st">"HC2"</span>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>ols</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Estimate   Std. Error   t value     Pr(&gt;|t|)     CI Lower
(Intercept)  4.902202008 0.0712861999 68.767896 0.000000e+00  4.762427137
educ         0.071498271 0.0036111667 19.799216 4.316524e-82  0.064417653
black       -0.168717410 0.0173999796 -9.696414 6.533265e-22 -0.202834531
smsa         0.172430654 0.0150653394 11.445521 1.017615e-29  0.142891194
south       -0.127691620 0.0151740941 -8.415107 5.996475e-17 -0.157444322
exper        0.071812773 0.0067378450 10.658122 4.654695e-26  0.058601501
expersq     -0.001889027 0.0003149664 -5.997550 2.242922e-09 -0.002506599
married     -0.033550125 0.0035795349 -9.372761 1.348435e-20 -0.040568721
                CI Upper   DF
(Intercept)  5.041976879 2995
educ         0.078578889 2995
black       -0.134600289 2995
smsa         0.201970114 2995
south       -0.097938918 2995
exper        0.085024046 2995
expersq     -0.001271454 2995
married     -0.026531529 2995</code></pre>
</div>
</div>
<p><strong>4.1 OLS Estimate</strong></p>
<p>The coefficient on educ is 0.071</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#4.2</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>iv <span class="ot">&lt;-</span> <span class="fu">iv_robust</span>(lwage <span class="sc">~</span> educ <span class="sc">+</span> black <span class="sc">+</span> smsa <span class="sc">+</span> south <span class="sc">+</span> exper <span class="sc">+</span> expersq <span class="sc">+</span> married <span class="sc">|</span> nearc4 <span class="sc">+</span> black <span class="sc">+</span> smsa <span class="sc">+</span> south <span class="sc">+</span> exper <span class="sc">+</span> expersq <span class="sc">+</span> married, <span class="at">data =</span> card, <span class="at">se_type =</span> <span class="st">"HC2"</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>iv</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Estimate   Std. Error   t value     Pr(&gt;|t|)     CI Lower
(Intercept)  3.988229477 0.8399956105  4.747917 2.151745e-06  2.341202728
educ         0.124893231 0.0490790159  2.544738 1.098575e-02  0.028661238
black       -0.118113004 0.0493318422 -2.394255 1.671531e-02 -0.214840728
smsa         0.144007839 0.0305020895  4.721245 2.451737e-06  0.084200673
south       -0.109013471 0.0230566857 -4.728063 2.371435e-06 -0.154222014
exper        0.094925153 0.0223207958  4.252767 2.176073e-05  0.051159510
expersq     -0.001965169 0.0003465968 -5.669900 1.564817e-08 -0.002644761
married     -0.029532543 0.0051528211 -5.731335 1.095519e-08 -0.039635970
                CI Upper   DF
(Intercept)  5.635256227 2995
educ         0.221125225 2995
black       -0.021385280 2995
smsa         0.203815006 2995
south       -0.063804928 2995
exper        0.138690796 2995
expersq     -0.001285577 2995
married     -0.019429116 2995</code></pre>
</div>
</div>
<p><strong>4.2 2SLS Estimate</strong></p>
<p>The coeﬀicient on educ is 0.125. It does match the Wald estimate from Section 3.2.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co">#4.3</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">modelsummary</span>(<span class="fu">list</span>(<span class="st">"OLS"</span> <span class="ot">=</span> ols, <span class="st">"2SLS"</span> <span class="ot">=</span> iv), <span class="at">coef_map =</span> <span class="fu">c</span>(<span class="st">"educ"</span> <span class="ot">=</span> <span class="st">"Years of Education"</span>), <span class="at">gof_map =</span> <span class="fu">c</span>(<span class="st">"nobs"</span>, <span class="st">"r.squared"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<!-- preamble start -->

    <script src="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js"></script>

    <script>
      // Create table-specific functions using external factory
      const tableFns_gpqb80difr0ql61q5aws = TinyTable.createTableFunctions("tinytable_gpqb80difr0ql61q5aws");
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: '4', j: 2 }, { i: '4', j: 3 } ], css_id: 'tinytable_css_20gh07w5nx6ojf146j4l',}, 
          { positions: [ { i: '2', j: 2 }, { i: '2', j: 3 } ], css_id: 'tinytable_css_otnhzows1911ynljs4ry',}, 
          { positions: [ { i: '1', j: 2 }, { i: '3', j: 2 }, { i: '1', j: 3 }, { i: '3', j: 3 } ], css_id: 'tinytable_css_rtbezxsskspc4a0k21c8',}, 
          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_y9deuwagrtd7hsakhj9w',}, 
          { positions: [ { i: '4', j: 1 } ], css_id: 'tinytable_css_e1822ppjb6r0fdd7buod',}, 
          { positions: [ { i: '2', j: 1 } ], css_id: 'tinytable_css_iwxy47kxwpc8e3h131pm',}, 
          { positions: [ { i: '1', j: 1 }, { i: '3', j: 1 } ], css_id: 'tinytable_css_acxbmq0krz2hnb4g5gho',}, 
          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_rtm09wgmvxiinca718cq',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  tableFns_gpqb80difr0ql61q5aws.styleCell(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css">
    <style>
    /* tinytable css entries after */
    #tinytable_gpqb80difr0ql61q5aws td.tinytable_css_20gh07w5nx6ojf146j4l, #tinytable_gpqb80difr0ql61q5aws th.tinytable_css_20gh07w5nx6ojf146j4l {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_gpqb80difr0ql61q5aws td.tinytable_css_otnhzows1911ynljs4ry, #tinytable_gpqb80difr0ql61q5aws th.tinytable_css_otnhzows1911ynljs4ry {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_gpqb80difr0ql61q5aws td.tinytable_css_rtbezxsskspc4a0k21c8, #tinytable_gpqb80difr0ql61q5aws th.tinytable_css_rtbezxsskspc4a0k21c8 { text-align: center }
    #tinytable_gpqb80difr0ql61q5aws td.tinytable_css_y9deuwagrtd7hsakhj9w, #tinytable_gpqb80difr0ql61q5aws th.tinytable_css_y9deuwagrtd7hsakhj9w {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_gpqb80difr0ql61q5aws td.tinytable_css_e1822ppjb6r0fdd7buod, #tinytable_gpqb80difr0ql61q5aws th.tinytable_css_e1822ppjb6r0fdd7buod {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_gpqb80difr0ql61q5aws td.tinytable_css_iwxy47kxwpc8e3h131pm, #tinytable_gpqb80difr0ql61q5aws th.tinytable_css_iwxy47kxwpc8e3h131pm {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_gpqb80difr0ql61q5aws td.tinytable_css_acxbmq0krz2hnb4g5gho, #tinytable_gpqb80difr0ql61q5aws th.tinytable_css_acxbmq0krz2hnb4g5gho { text-align: left }
    #tinytable_gpqb80difr0ql61q5aws td.tinytable_css_rtm09wgmvxiinca718cq, #tinytable_gpqb80difr0ql61q5aws th.tinytable_css_rtm09wgmvxiinca718cq {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    </style>
    <div class="container">
      <table class="tinytable" id="tinytable_gpqb80difr0ql61q5aws" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        
        <thead>
              <tr>
                <th scope="col" data-row="0" data-col="1"> </th>
                <th scope="col" data-row="0" data-col="2">OLS</th>
                <th scope="col" data-row="0" data-col="3">2SLS</th>
              </tr>
        </thead>
        
        <tbody>
                <tr>
                  <td data-row="1" data-col="1">Years of Education</td>
                  <td data-row="1" data-col="2">0.071</td>
                  <td data-row="1" data-col="3">0.125</td>
                </tr>
                <tr>
                  <td data-row="2" data-col="1"></td>
                  <td data-row="2" data-col="2">(0.004)</td>
                  <td data-row="2" data-col="3">(0.049)</td>
                </tr>
                <tr>
                  <td data-row="3" data-col="1">Num.Obs.</td>
                  <td data-row="3" data-col="2">3003</td>
                  <td data-row="3" data-col="3">3003</td>
                </tr>
                <tr>
                  <td data-row="4" data-col="1">R2</td>
                  <td data-row="4" data-col="2">0.313</td>
                  <td data-row="4" data-col="3">0.259</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div>
<p><strong>4.4 Why do OLS and 2SLS differ?</strong></p>
<p>(a) The coefficient of the 2SLS is greater.</p>
<p>(b) Card (1995) interprets the finding that 2SLS &gt; OLS as evidence of downward bias in OLS. One thing that could cause OLS to underestimate the return to education is measurement error. If we think about educ, it is an endogenous variable that measures years of completed education. If in fact this variable is measured incorrectly, it could indicate that education has a greater effect on wage than the model expected, this is attenuation bias.</p>
<p>(c) I believe the estimate from the 2SLS is more credible as a causal estimate of the effect of education on wages. This is because the OLS estimate is at risk of the omitted variable bias, as the included variables are all at the subjective disgression of the person running the model. With 2SLS, the model is able to use only variation in education due to the near college instrumental variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#4.5</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>ols_iq <span class="ot">&lt;-</span> <span class="fu">lm_robust</span>(lwage <span class="sc">~</span> educ <span class="sc">+</span> IQ <span class="sc">+</span> black <span class="sc">+</span> smsa <span class="sc">+</span> south <span class="sc">+</span> exper <span class="sc">+</span> expersq <span class="sc">+</span> married,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> card, <span class="at">se_type =</span> <span class="st">"HC2"</span>)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>ols_iq</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Estimate   Std. Error   t value      Pr(&gt;|t|)     CI Lower
(Intercept)  4.624820266 0.1106111619 41.811515 7.250324e-277  4.407898361
educ         0.067568681 0.0050672360 13.334426  5.821735e-39  0.057631216
IQ           0.002500262 0.0007491806  3.337329  8.609879e-04  0.001031028
black       -0.120030879 0.0270219343 -4.441980  9.387896e-06 -0.173024170
smsa         0.162782345 0.0184132040  8.840522  2.006318e-18  0.126671818
south       -0.083180925 0.0183563649 -4.531449  6.195149e-06 -0.119179983
exper        0.083230844 0.0092631008  8.985203  5.709939e-19  0.065064780
expersq     -0.002350153 0.0004642726 -5.062012  4.518801e-07 -0.003260648
married     -0.029240623 0.0044083448 -6.633016  4.194221e-11 -0.037885922
                CI Upper   DF
(Intercept)  4.841742172 2051
educ         0.077506145 2051
IQ           0.003969496 2051
black       -0.067037588 2051
smsa         0.198892871 2051
south       -0.047181867 2051
exper        0.101396909 2051
expersq     -0.001439659 2051
married     -0.020595324 2051</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>twosls_iq <span class="ot">&lt;-</span> <span class="fu">iv_robust</span>(lwage <span class="sc">~</span> educ <span class="sc">+</span> IQ <span class="sc">+</span> black <span class="sc">+</span> smsa <span class="sc">+</span> south <span class="sc">+</span> exper <span class="sc">+</span> expersq <span class="sc">+</span> married <span class="sc">|</span> nearc4 <span class="sc">+</span> IQ <span class="sc">+</span> black <span class="sc">+</span> smsa <span class="sc">+</span> south <span class="sc">+</span> exper <span class="sc">+</span> expersq <span class="sc">+</span> married, <span class="at">data =</span> card, <span class="at">se_type =</span> <span class="st">"HC2"</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>twosls_iq</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Estimate   Std. Error    t value     Pr(&gt;|t|)     CI Lower
(Intercept)  4.1254833454 0.8039381042  5.1315932 3.143855e-07  2.548863208
educ         0.1093899302 0.0669607951  1.6336414 1.024876e-01 -0.021928311
IQ           0.0004228523 0.0034135214  0.1238757 9.014258e-01 -0.006271477
black       -0.1233784512 0.0280423967 -4.3997114 1.139525e-05 -0.178372993
smsa         0.1536399386 0.0239013796  6.4280783 1.602608e-10  0.106766434
south       -0.0857686314 0.0190205986 -4.5092498 6.872948e-06 -0.123070332
exper        0.1035065280 0.0339813212  3.0459830 2.348745e-03  0.036865035
expersq     -0.0027889965 0.0008630306 -3.2316312 1.250362e-03 -0.004481504
married     -0.0274086703 0.0053001348 -5.1713157 2.550570e-07 -0.037802878
                CI Upper   DF
(Intercept)  5.702103483 2051
educ         0.240708171 2051
IQ           0.007117182 2051
black       -0.068383910 2051
smsa         0.200513443 2051
south       -0.048466930 2051
exper        0.170148021 2051
expersq     -0.001096489 2051
married     -0.017014463 2051</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fl">0.125</span> <span class="sc">-</span> <span class="fl">0.109</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.016</code></pre>
</div>
</div>
<p><strong>4.5 Adding IQ as a control</strong></p>
<p>(a) Including IQ changes the OLS coeﬀicient on educ by decreasing it to 0.068 from 0.071.</p>
<p>(b) The 2SLS estimate decreases to 0.109 from 0.125 or by 0.016. It changes a bit but not extremely susbtantially with 0.016 being a relatively smaller value.</p>
<p>(c) These comparisons between part (a) and part (b) suggest that IQ is one source of bias that impacts the model as it causes both the OLS and 2SLS estimates to decrease. However, the OLS and 2SLS estimates still remain relatively different indicating there are other reasonings why the IV estimate is greater than OLS. it is also interesting to note that OLS changes more than the 2SLS which makes sense given that the IV would likely eliminate some of the OVB in the 2SLS that the OLS does not account for.</p>
</section>
<section id="interpretation-and-late" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-and-late">5 Interpretation and LATE</h4>
<p><strong>5.1 Who are the compliers?</strong> In this context, the compliers are individuals who would not have otherwise gone to college but decided to go to college because they happened to grow up near a 4-year college. For instance, these could be people that living near a college allowed for the costs associated with going to college to be cheaper so they could go to a college because they lived near it.</p>
<p><strong>5.2 Write the LATE interpretation</strong></p>
<p>Write a single careful sentence interpreting the 2SLS coeﬀicient as a LATE. Your sentence should specify:</p>
<p>The causal effect of an additional year of schooling on wages is about a 12.5% increase in expected wage for those individuals whose educational attainment increased because they lived near a college, identified by variation in nearc4, as living near a college decreases the cost of attending univeristy thereby changing education.</p>
<p><strong>5.3 External validity</strong></p>
<p>Card finds a 2SLS estimate around 12–13% return to each additional year of education. In this case, the LATE is likely not going to be the same as the ATE (the return for the average person in the sample). This is because the compliers, the men who went to more school because they happened to live near a college, are likely to have higher returns to education than the typical person. When we think about these compliers, they likely are more economically disadvantaged and would not have had the opportunity to get increased schooling. However, because of where they live, they were able to acquire more education, and probably experience more gains from an additional year of schooling than the average person. This is because this additional schooling for compliers could open up all sorts of doors for the compliers that they would not of otherwise have had access too with their financial backgrounds, but the average person might have had more access to. As a result, the LATE is probably bigger than the ATE which makes sense considering the IV estimate is larger than the ols one.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>